# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  lix = {
    pname = "lix";
    version = "e4d74bad335b5754b55da57ac53a86dfb07e4a4d";
    src = fetchFromGitHub {
      owner = "lix-project";
      repo = "lix";
      rev = "e4d74bad335b5754b55da57ac53a86dfb07e4a4d";
      fetchSubmodules = false;
      sha256 = "sha256-rp0pEO8p4PjL40o+sM/YpDTY/nKQlzKpRGNftw9+3fA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-rp0pEO8p4PjL40o+sM_YpDTY_nKQlzKpRGNftw9+3fA=/Cargo.lock";
      outputHashes = {
        "zngur-0.10.0" = "sha256-pad2C+fXiyePnrkhDgRXgdmt7rxghEY4RW9al3qh7ko=";
      };
    };
    date = "2026-09-08";
  };
  nil = {
    pname = "nil";
    version = "205c8ba65a7f956d7837a710794001b3515c65ff";
    src = fetchgit {
      url = "https://github.com/oxalica/nil.git";
      rev = "205c8ba65a7f956d7837a710794001b3515c65ff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-F+MFs5cJbqcrlu/6BzQhNwF7Ih26yG9Yg9p4xyDz5eY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-F+MFs5cJbqcrlu_6BzQhNwF7Ih26yG9Yg9p4xyDz5eY=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-07-26";
  };
}
