# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  lix = {
    pname = "lix";
    version = "053cb56688e2a7f24beccfab8bc9924a72148a88";
    src = fetchFromGitHub {
      owner = "lix-project";
      repo = "lix";
      rev = "053cb56688e2a7f24beccfab8bc9924a72148a88";
      fetchSubmodules = false;
      sha256 = "sha256-QVj2X6PoadoM82Uaim8rEC5c+uqBji/XZYE4ApjzBwo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-QVj2X6PoadoM82Uaim8rEC5c+uqBji_XZYE4ApjzBwo=/Cargo.lock";
      outputHashes = {
        "zngur-0.10.0" = "sha256-pad2C+fXiyePnrkhDgRXgdmt7rxghEY4RW9al3qh7ko=";
      };
    };
    date = "2026-09-17";
  };
  nil = {
    pname = "nil";
    version = "205c8ba65a7f956d7837a710794001b3515c65ff";
    src = fetchgit {
      url = "https://github.com/oxalica/nil.git";
      rev = "205c8ba65a7f956d7837a710794001b3515c65ff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-F+MFs5cJbqcrlu/6BzQhNwF7Ih26yG9Yg9p4xyDz5eY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-F+MFs5cJbqcrlu_6BzQhNwF7Ih26yG9Yg9p4xyDz5eY=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-07-26";
  };
}
