# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  lix = {
    pname = "lix";
    version = "326fd84d3e7da0d0b00f5f2b72c4300812e26576";
    src = fetchFromGitHub {
      owner = "lix-project";
      repo = "lix";
      rev = "326fd84d3e7da0d0b00f5f2b72c4300812e26576";
      fetchSubmodules = false;
      sha256 = "sha256-7imce21SglnodNgi7eiZAmZucz5cJFaFpffCWOXT8Xc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-7imce21SglnodNgi7eiZAmZucz5cJFaFpffCWOXT8Xc=/Cargo.lock";
      outputHashes = {
        "zngur-0.10.0" = "sha256-q8mkHbZwrgLF61Esbd9nK9y8GnZqHWzSubY9ERibBEo=";
      };
    };
    date = "2026-07-25";
  };
  nil = {
    pname = "nil";
    version = "205c8ba65a7f956d7837a710794001b3515c65ff";
    src = fetchgit {
      url = "https://github.com/oxalica/nil.git";
      rev = "205c8ba65a7f956d7837a710794001b3515c65ff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-F+MFs5cJbqcrlu/6BzQhNwF7Ih26yG9Yg9p4xyDz5eY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-F+MFs5cJbqcrlu_6BzQhNwF7Ih26yG9Yg9p4xyDz5eY=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-07-26";
  };
}
